version: "3"
services:
  server:
    build: "./server"
    depends_on:
      - server-db
    environment:
      - DB_URI=mysql://root:password@server-db/db?charset=UTF8
    ports:
      - 7000:7000
    volumes:
      - ./server:/opt/app

  server-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:latest
    ports:
      - 0.0.0.0:5100:3306