version: "3"
services:
  api-gateway:
    build: "./api-gateway"
    depends_on:
      - adverts-service
      - users-service
    ports:
      - 7000:7000
    volumes:
      - ./api-gateway:/opt/app
  adverts-service:
    build: "./adverts-service"
    depends_on:
      - adverts-service-db
    environment:
      - DB_URI=mysql://root:password@adverts-service-db/db?charset=UTF8
    ports:
      - 7100:7100
    volumes:
      - ./adverts-service:/opt/app
  
  adverts-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:latest
    ports:
      - 0.0.0.0:7200:3306

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    environment:
      - DB_URI=mysql://root:password@users-service-db/db?charset=UTF8
    ports:
      - 7101:7101
    volumes:
      - ./users-service:/opt/app 

  users-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:latest
    ports:
      - 0.0.0.0:7201:3306